# Use the official .NET SDK image to build the app
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY Ainm.API/*.csproj ./Ainm.API/
RUN dotnet restore ./Ainm.API/Ainm.API.csproj

# Copy everything else and build
COPY . ./
WORKDIR /app/Ainm.API
RUN dotnet publish -c Release -o /app/out

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/out ./

EXPOSE 80
ENTRYPOINT ["dotnet", "Ainm.API.dll"]