# Use the official .NET SDK image to build the app
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copy only the csproj and restore as a separate layer
COPY ./Ainm.API/*.csproj ./Ainm.API/
WORKDIR /src/Ainm.API
RUN dotnet restore

# Copy the rest of the source code
COPY ./Ainm.API/. ./
RUN dotnet publish -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /src/Ainm.API/out ./

# Expose port 80 (the default for ASP.NET Core)
EXPOSE 80

# Start the app
ENTRYPOINT ["dotnet", "Ainm.API.dll"]